digirss/digirss/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from rssapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main', views.main, name='main'),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^rssapp/',include('rssapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

digirss/rssapp/urls.py
from django.conf.urls import url
from rssapp import views
# SET THE NAMESPACE!
app_name = 'rssapp'

urlpatterns=[
    url(r'^main/$', views.main, name='main'),
    url(r'^user_register/$',views.user_register,name='user_register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

digirss/rssapp/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser


class Feeds(models.Model):
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=2048)
    desc = models.TextField(null=True, blank=True)
    date = models.DateTimeField()
    favourite = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='user_favourite')


class CustomUser(AbstractUser):
    feed = models.ManyToManyField(Feeds, blank=True)
    pass

digirss/rssapp/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)

digirss/rssapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import feedparser

from rssapp.forms import RegisterForm


def index(request):
    return render(request, 'rssapp/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Save session as cookie to login the user
            login(request, user)
            # Success, now let's login the user.
            return render(request, 'rssapp/account.html')
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, 'rssapp/login.html',
                          {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, 'rssapp/login.html')


def user_register(request):
    # if this is a POST request we need to process the form data
    template = 'rssapp/register.html'

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email already exists.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords do not match.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.phone_number = form.cleaned_data['phone_number']
                user.save()

                # Login the user
                login(request, user)

                # redirect to accounts page:
                return HttpResponseRedirect('/rssapp/account')

    # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})


def main(request):
    if request.GET.get("url"):

        url = request.GET["url"]

        feed = feedparser.parse(url)  # Parsing XML data

    else:

        feed = None

    return render(request, 'rssapp/main.html', {'feed': feed, })

digirss/templates/rssapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>DigiRSS</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/rssapp/">DigiRSS</a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/rssapp/register">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row well ml-t">
                <div class="col-lg-8 col-md-8">
                    <h4>Developed by: <a href="https://carlofontanos.com" target="_blank">Carl Victor C. Fontanos</a></h4>
                </div>
                <div class="col-lg-4 col-md-4">
                    <p class="m-t">Copyright &copy <a href="https://carlofontanos.com" target="_blank">www.carlofontanos.com</a> 2017</p>
                    <p>All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

digirss/templates/rssapp/index.html
{% extends "rssapp/base.html" %}
{% block body_block %}<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>{% endblock %}

digirss/templates/rssapp/login.html
{% extends "rssapp/base.html" %}

{% block content %}
    <div class="container">
        <form action="{% url 'rssapp:user_login' %}" method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <div class="col-md-6">
                                <input name="password" type="password" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Login" class="btn btn-success" /> &nbsp;
                            <a href="/rssapp/register">or Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

digirss/templates/rssapp/main.html
{% extends 'rssapp/mbase.html' %}

 

{% block body %}

<br />

<form class="form-inline">

<div class="form-group mx-sm-3 mb-2">

<label for="inputPassword2" class="sr-only">Feeds</label>

<input type="text" class="form-control" placeholder="paste link" name="url">

</div>

<button type="submit" class="btn btn-primary mb-2">Search</button>

</form>

{% if feed %}

<h2>{{ feed.feed.title }}</h2>

{% if feed.entries %}

{% for entry in feed.entries %}

<div class="card">

<div class="card-header">

Feed

</div>

<div class="card-body">

<h5 class="card-title">Headline: {{ entry.title }}</h5>

<p class="card-text">Description: {{ entry.description }}</p>

<a href="{{ entry.link }}" class="btn btn-primary">Visit Link</a>

</div>

</div><p>{{ entry.published }}</p>

 

{% endfor %}

{% endif %}

{% else %}

<br />

<p>Enter your favorite RSS feed above.</p>

{% endif %}

 

{{ feed2 }}

 

{% endblock %}

digirss/templates/rssapp/mbase.html
<!DOCTYPE html>
<html>

<script src=”https://code.jquery.com/jquery-3.3.1.slim.min.js”></script>
<script src=”https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js”></script>
<script src=”https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js”></script>
<link rel=”stylesheet” href=”https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css”>
<head>

<title>Django RSS Reader</title>

</head>

<nav class=“navbar navbar-expand-sm bg-dark navbar-dark”>

<ul class=“navbar-nav”>

<li class=“nav-item active”>

<a class=“nav-link” href=“/”>Home</a>

</ul>

</nav>

<body>

{% block body %}{% endblock %}

</body>

</html>

digirss/templates/rssapp/registration.html
{% extends "rssapp/base.html" %}

{% block content %}
    <div class="container">
        <form action="{% url 'rssapp:user_register' %}" method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Register</div>
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}

                        <div class="form-group clearfix">
                            <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-right">Email<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right">Confirm password:</label>
                            <div class="col-md-6">
                                {{ form.password_repeat }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-right">First Name:</label>
                            <div class="col-md-6">
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-right">Last Name:</label>
                            <div class="col-md-6">
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.phone_number.id_for_label }}" class="col-md-4 control-label text-right">Phone Number:</label>
                            <div class="col-md-6">
                                {{ form.phone_number }}
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input type="submit" value="Register" class="btn btn-success">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}